type: dev-environment
# The name is optional, if not specified, generated randomly
name: vscode-optimum-tpu

# Using a Docker image with a fix instead of the official one
# More details at https://github.com/huggingface/optimum-tpu/pull/87
image: dstackai/optimum-tpu:llama31
# Required environment variables
env:
  - HF_TOKEN
ide: vscode

resources:
  # Required resources
  gpu: v5litepod-4

# Use either spot or on-demand instances
spot_policy: auto
