"""Add GatewayModel pipeline columns

Revision ID: 66c2fdda33c2
Revises: a8ed24fd7f90
Create Date: 2026-02-19 09:42:40.392357+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "66c2fdda33c2"
down_revision = "a8ed24fd7f90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lock_expires_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "lock_token", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.add_column(sa.Column("lock_owner", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("lock_owner")
        batch_op.drop_column("lock_token")
        batch_op.drop_column("lock_expires_at")

    # ### end Alembic commands ###
