"""Add pipeline indexes for compute and placement groups

Revision ID: a8ed24fd7f90
Revises: 9c2a227b0154
Create Date: 2026-02-18 11:22:25.972000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8ed24fd7f90"
down_revision = "9c2a227b0154"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        if op.get_context().dialect.name == "postgresql":
            # Concurrent index ops can fail midway, leaving invalid indexes behind.
            # Use DROP INDEX IF EXISTS so the migration can be retried safely.
            op.drop_index(
                "ix_compute_groups_pipeline_fetch_q",
                table_name="compute_groups",
                if_exists=True,
                postgresql_concurrently=True,
            )
            op.drop_index(
                "ix_placement_groups_pipeline_fetch_q",
                table_name="placement_groups",
                if_exists=True,
                postgresql_concurrently=True,
            )
        op.create_index(
            "ix_compute_groups_pipeline_fetch_q",
            "compute_groups",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            postgresql_where=sa.text("(status NOT IN ('TERMINATED'))"),
            sqlite_where=sa.text("(status NOT IN ('TERMINATED'))"),
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_placement_groups_pipeline_fetch_q",
            "placement_groups",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            postgresql_where=sa.text("deleted IS FALSE"),
            sqlite_where=sa.text("deleted = 0"),
            postgresql_concurrently=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_placement_groups_pipeline_fetch_q",
            "placement_groups",
            if_exists=True,
            postgresql_concurrently=True,
        )
        op.drop_index(
            "ix_compute_groups_pipeline_fetch_q",
            "compute_groups",
            if_exists=True,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
