"""Add GatewayModel deleted columns

Revision ID: d911914ecf17
Revises: 66c2fdda33c2
Create Date: 2026-02-20 08:40:11.616560+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "d911914ecf17"
down_revision = "66c2fdda33c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("to_be_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "deleted_by_user_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_gateways_deleted_by_user_id_users"),
            "users",
            ["deleted_by_user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_gateways_deleted_by_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("deleted_by_user_id")
        batch_op.drop_column("to_be_deleted")

    # ### end Alembic commands ###
