"""Add ix_volumes_pipeline_fetch_q index

Revision ID: 9a363c3cbe04
Revises: ccfac6ac7924
Create Date: 2026-02-24 09:45:54.068288+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a363c3cbe04"
down_revision = "ccfac6ac7924"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_volumes_pipeline_fetch_q",
            table_name="volumes",
            if_exists=True,
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_volumes_pipeline_fetch_q",
            "volumes",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            sqlite_where=sa.text("deleted = 0"),
            postgresql_where=sa.text("deleted IS FALSE"),
            postgresql_concurrently=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_volumes_pipeline_fetch_q",
            table_name="volumes",
            if_exists=True,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
