"""Add GatewayModel.to_be_deleted

Revision ID: 3160b6c59d94
Revises: 66c2fdda33c2
Create Date: 2026-02-20 09:14:31.650140+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3160b6c59d94"
down_revision = "66c2fdda33c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("to_be_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("to_be_deleted")

    # ### end Alembic commands ###
