"""Add exports

Revision ID: 5e8c7a9202bc
Revises: 46150101edec
Create Date: 2026-03-04 22:21:54.971260+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "5e8c7a9202bc"
down_revision = "46150101edec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exports",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_exports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
        sa.UniqueConstraint("project_id", "name", name="uq_exports_project_id_name"),
    )
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exports_project_id"), ["project_id"], unique=False)

    op.create_table(
        "exported_fleets",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("export_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("fleet_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_id"],
            ["exports.id"],
            name=op.f("fk_exported_fleets_export_id_exports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleets.id"],
            name=op.f("fk_exported_fleets_fleet_id_fleets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exported_fleets")),
        sa.UniqueConstraint("export_id", "fleet_id", name="uq_exported_fleets_export_id_fleet_id"),
    )
    with op.batch_alter_table("exported_fleets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exported_fleets_export_id"), ["export_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exported_fleets_fleet_id"), ["fleet_id"], unique=False
        )

    op.create_table(
        "imports",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("export_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_id"],
            ["exports.id"],
            name=op.f("fk_imports_export_id_exports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_imports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
        sa.UniqueConstraint("project_id", "export_id", name="uq_imports_project_id_export_id"),
    )
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_imports_export_id"), ["export_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_imports_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_imports_project_id"))
        batch_op.drop_index(batch_op.f("ix_imports_export_id"))

    op.drop_table("imports")
    with op.batch_alter_table("exported_fleets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exported_fleets_fleet_id"))
        batch_op.drop_index(batch_op.f("ix_exported_fleets_export_id"))

    op.drop_table("exported_fleets")
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exports_project_id"))

    op.drop_table("exports")
    # ### end Alembic commands ###
