"""Add resource exports imports

Revision ID: ea7cca121fcb
Revises: 46150101edec
Create Date: 2026-03-02 13:45:57.118841+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "ea7cca121fcb"
down_revision = "46150101edec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_exports",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_resource_exports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_exports")),
        sa.UniqueConstraint("project_id", "name", name="uq_resource_exports_project_id_name"),
    )
    with op.batch_alter_table("resource_exports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_exports_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "exported_fleets",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "resource_export_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("fleet_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleets.id"],
            name=op.f("fk_exported_fleets_fleet_id_fleets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_export_id"],
            ["resource_exports.id"],
            name=op.f("fk_exported_fleets_resource_export_id_resource_exports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exported_fleets")),
        sa.UniqueConstraint(
            "resource_export_id", "fleet_id", name="uq_exported_fleets_resource_export_id_fleet_id"
        ),
    )
    with op.batch_alter_table("exported_fleets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exported_fleets_fleet_id"), ["fleet_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exported_fleets_resource_export_id"),
            ["resource_export_id"],
            unique=False,
        )

    op.create_table(
        "resource_imports",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column(
            "resource_export_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_resource_imports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_export_id"],
            ["resource_exports.id"],
            name=op.f("fk_resource_imports_resource_export_id_resource_exports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_imports")),
        sa.UniqueConstraint(
            "project_id",
            "resource_export_id",
            name="uq_resource_imports_project_id_resource_export_id",
        ),
    )
    with op.batch_alter_table("resource_imports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_imports_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resource_imports_resource_export_id"),
            ["resource_export_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource_imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_imports_resource_export_id"))
        batch_op.drop_index(batch_op.f("ix_resource_imports_project_id"))

    op.drop_table("resource_imports")
    with op.batch_alter_table("exported_fleets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exported_fleets_resource_export_id"))
        batch_op.drop_index(batch_op.f("ix_exported_fleets_fleet_id"))

    op.drop_table("exported_fleets")
    with op.batch_alter_table("resource_exports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_exports_project_id"))

    op.drop_table("resource_exports")
    # ### end Alembic commands ###
