"""Add ix_instances_pipeline_fetch_q index

Revision ID: 297c68450cc8
Revises: 8e8647f20aa4
Create Date: 2026-03-04 07:51:02.855596+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "297c68450cc8"
down_revision = "8e8647f20aa4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_instances_pipeline_fetch_q",
            table_name="instances",
            if_exists=True,
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_instances_pipeline_fetch_q",
            "instances",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            sqlite_where=sa.text("deleted = 0"),
            postgresql_where=sa.text("deleted IS FALSE"),
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_instances_pipeline_fetch_q",
            table_name="instances",
            if_exists=True,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
