"""Add FleetModel current master instance

Revision ID: 9cb8e4e4d986
Revises: 297c68450cc8
Create Date: 2026-03-04 10:15:00.000000+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cb8e4e4d986"
down_revision = "297c68450cc8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_master_instance_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.drop_column("current_master_instance_id")
    # ### end Alembic commands ###
