"""Add ix_fleets_pipeline_fetch_q index

Revision ID: 46150101edec
Revises: d21d3e61de27
Create Date: 2026-03-02 05:30:07.196407+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46150101edec"
down_revision = "d21d3e61de27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_fleets_pipeline_fetch_q",
            table_name="fleets",
            if_exists=True,
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_fleets_pipeline_fetch_q",
            "fleets",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            sqlite_where=sa.text("deleted = 0"),
            postgresql_where=sa.text("deleted IS FALSE"),
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_fleets_pipeline_fetch_q",
            table_name="fleets",
            if_exists=True,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
