"""Add ix_runs_pipeline_fetch_q index

Revision ID: c1c2ecaee45c
Revises: 7099b48e72a9
Create Date: 2026-03-24 05:28:50.925623+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1c2ecaee45c"
down_revision = "7099b48e72a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_runs_pipeline_fetch_q",
            table_name="runs",
            if_exists=True,
            postgresql_concurrently=True,
        )
        op.create_index(
            "ix_runs_pipeline_fetch_q",
            "runs",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            sqlite_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"),
            postgresql_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"),
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(
            "ix_runs_pipeline_fetch_q",
            table_name="runs",
            if_exists=True,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
