"""Add JobModel.graceful_termination_attempts

Revision ID: aae8323e38f2
Revises: c1c2ecaee45c
Create Date: 2026-03-30 06:19:29.078302+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aae8323e38f2"
down_revision = "c1c2ecaee45c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("graceful_termination_attempts", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("graceful_termination_attempts")

    # ### end Alembic commands ###
