"""Add JobModel.graceful_termination_attempts

Revision ID: e9d81c97c042
Revises: 59e328ced74c
Create Date: 2026-03-30 08:41:29.308250+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9d81c97c042"
down_revision = "59e328ced74c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("graceful_termination_attempts", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("graceful_termination_attempts")

    # ### end Alembic commands ###
