"""Add JobMetricsPoint.job_id index

Revision ID: ad8c50120507
Revises: e9d81c97c042
Create Date: 2026-04-03 10:43:18.440334+00:00

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad8c50120507"
down_revision = "e9d81c97c042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_metrics_points", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_metrics_points_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_metrics_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_metrics_points_job_id"))

    # ### end Alembic commands ###
