"""Add service_router_worker_sync for router-worker reconcile pipeline.

Revision ID: 94fcd7e38b7e
Revises: 1b9e2e7e7d35
Create Date: 2026-04-15 05:15:50.107554+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "94fcd7e38b7e"
down_revision = "1b9e2e7e7d35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_router_worker_sync",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("deleted", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column(
            "last_processed_at", dstack._internal.server.models.NaiveDateTime(), nullable=False
        ),
        sa.Column(
            "lock_expires_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
        ),
        sa.Column("lock_token", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
        sa.Column("lock_owner", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_service_router_worker_sync_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_router_worker_sync")),
    )
    with op.batch_alter_table("service_router_worker_sync", schema=None) as batch_op:
        batch_op.create_index(
            "ix_service_router_worker_sync_pipeline_fetch_q",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
            sqlite_where=sa.text("deleted = 0"),
            postgresql_where=sa.text("deleted IS FALSE"),
        )
        batch_op.create_index(
            batch_op.f("ix_service_router_worker_sync_run_id"), ["run_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_router_worker_sync", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_router_worker_sync_run_id"))
        batch_op.drop_index(
            "ix_service_router_worker_sync_pipeline_fetch_q",
            sqlite_where=sa.text("deleted = 0"),
            postgresql_where=sa.text("deleted IS FALSE"),
        )

    op.drop_table("service_router_worker_sync")
    # ### end Alembic commands ###
