"""Add JobModel.image_pull_progress

Revision ID: f48b23790053
Revises: 94fcd7e38b7e
Create Date: 2026-04-18 18:22:47.121819+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f48b23790053"
down_revision = "94fcd7e38b7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_pull_progress", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("image_pull_progress")

    # ### end Alembic commands ###
