"""Add ExportedGatewayModel

Revision ID: db3679abd063
Revises: 05c351d08f6b
Create Date: 2026-04-29 17:00:29.551669+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "db3679abd063"
down_revision = "05c351d08f6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exported_gateways",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("export_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "gateway_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["export_id"],
            ["exports.id"],
            name=op.f("fk_exported_gateways_export_id_exports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
            name=op.f("fk_exported_gateways_gateway_id_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exported_gateways")),
        sa.UniqueConstraint(
            "export_id", "gateway_id", name="uq_exported_gateways_export_id_gateway_id"
        ),
    )
    with op.batch_alter_table("exported_gateways", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exported_gateways_export_id"), ["export_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exported_gateways_gateway_id"), ["gateway_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exported_gateways", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exported_gateways_gateway_id"))
        batch_op.drop_index(batch_op.f("ix_exported_gateways_export_id"))

    op.drop_table("exported_gateways")
    # ### end Alembic commands ###
