"""Add InstanceModel.skip_min_processing_interval

Revision ID: 05c351d08f6b
Revises: 8c1f8f4fcb47
Create Date: 2026-04-27 10:30:00.000000+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05c351d08f6b"
down_revision = "8c1f8f4fcb47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skip_min_processing_interval",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("skip_min_processing_interval")
    # ### end Alembic commands ###
