"""Add JobModel.skip_min_processing_interval

Revision ID: d9f6d27f0c41
Revises: 82b671d9c5ab
Create Date: 2026-04-24 07:15:00.000000+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9f6d27f0c41"
down_revision = "82b671d9c5ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skip_min_processing_interval",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("skip_min_processing_interval")
    # ### end Alembic commands ###
