"""Add InstanceModel.provisioning_job_id for placeholder instances

Revision ID: 82b671d9c5ab
Revises: f48b23790053
Create Date: 2026-04-24 05:42:14.856254+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "82b671d9c5ab"
down_revision = "f48b23790053"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provisioning_job_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("provisioning_job_id")

    # ### end Alembic commands ###
