"""Add InstanceModel.provisioning_job_id for placeholder instances

Revision ID: 13ae4ee1df6a
Revises: 94fcd7e38b7e
Create Date: 2026-04-23 09:07:24.552837+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "13ae4ee1df6a"
down_revision = "94fcd7e38b7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provisioning_job_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("provisioning_job_id")

    # ### end Alembic commands ###
