"""Add RunModel.skip_min_processing_interval

Revision ID: 8c1f8f4fcb47
Revises: d9f6d27f0c41
Create Date: 2026-04-27 07:20:00.000000+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c1f8f4fcb47"
down_revision = "d9f6d27f0c41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skip_min_processing_interval",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("skip_min_processing_interval")
    # ### end Alembic commands ###
