"""Add GatewayModel.forbid_new_services

Revision ID: 205690dfeec2
Revises: db3679abd063
Create Date: 2026-05-07 17:21:23.415019+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "205690dfeec2"
down_revision = "db3679abd063"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "forbid_new_services", sa.Boolean(), server_default=sa.false(), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("forbid_new_services")

    # ### end Alembic commands ###
