"""Add ExportModel.is_global

Revision ID: 201cb7ccd0d3
Revises: 205690dfeec2
Create Date: 2026-05-13 07:24:06.321892+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "201cb7ccd0d3"
down_revision = "205690dfeec2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_global", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exports", schema=None) as batch_op:
        batch_op.drop_column("is_global")

    # ### end Alembic commands ###
