"""Add GatewayComputeModel.gateway_id

Revision ID: b7609b94ea4d
Revises: 201cb7ccd0d3
Create Date: 2026-06-01 19:11:30.641417+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7609b94ea4d"
down_revision = "201cb7ccd0d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("replica_num", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "gateway_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_gateway_computes_gateway_id_gateways"),
            "gateways",
            ["gateway_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_gateway_computes_gateway_id_gateways"), type_="foreignkey"
        )
        batch_op.drop_column("gateway_id")
        batch_op.drop_column("replica_num")

    # ### end Alembic commands ###
