"""add endpoint agent attempts

Revision ID: 4e1d6c2a9b77
Revises: 03efb71a1563
Create Date: 2026-07-06 17:00:00.000000+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "4e1d6c2a9b77"
down_revision = "03efb71a1563"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_agent_attempts",
        sa.Column(
            "endpoint_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("attempt_num", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("workspace_path", sa.Text(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("process_host", sa.String(length=255), nullable=True),
        sa.Column("progress_log_offset", sa.BigInteger(), nullable=False),
        sa.Column("stdout_log_offset", sa.BigInteger(), nullable=False),
        sa.Column("stderr_log_offset", sa.BigInteger(), nullable=False),
        sa.Column("max_agent_budget", sa.Float(), nullable=True),
        sa.Column("spent_agent_budget", sa.Float(), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column("updated_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column("finished_at", dstack._internal.server.models.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
            name=op.f("fk_endpoint_agent_attempts_endpoint_id_endpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "endpoint_id", "attempt_num", name=op.f("pk_endpoint_agent_attempts")
        ),
    )
    with op.batch_alter_table("endpoint_agent_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_endpoint_agent_attempts_endpoint_id"), ["endpoint_id"], unique=False
        )
        batch_op.create_index(
            "ix_endpoint_agent_attempts_endpoint_status",
            ["endpoint_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_endpoint_agent_attempts_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("endpoint_agent_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_endpoint_agent_attempts_status"))
        batch_op.drop_index("ix_endpoint_agent_attempts_endpoint_status")
        batch_op.drop_index(batch_op.f("ix_endpoint_agent_attempts_endpoint_id"))

    op.drop_table("endpoint_agent_attempts")
    # ### end Alembic commands ###
