"""add endpoints

Revision ID: 03efb71a1563
Revises: e9c5e7e26c78
Create Date: 2026-07-03 12:43:58.140371+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "03efb71a1563"
down_revision = "e9c5e7e26c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoints",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("user_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "service_run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.Column("configuration", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("provisioning_method", sa.String(length=100), nullable=True),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column(
            "last_processed_at", dstack._internal.server.models.NaiveDateTime(), nullable=False
        ),
        sa.Column(
            "lock_expires_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
        ),
        sa.Column("lock_token", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
        sa.Column("lock_owner", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_endpoints_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_run_id"], ["runs.id"], name=op.f("fk_endpoints_service_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_endpoints_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoints")),
        sa.UniqueConstraint("project_id", "name", name="uq_endpoints_project_id_name"),
    )
    with op.batch_alter_table("endpoints", schema=None) as batch_op:
        batch_op.create_index(
            "ix_endpoints_pipeline_fetch_q",
            [sa.literal_column("last_processed_at ASC")],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_endpoints_status"), ["status"], unique=False)

    op.create_table(
        "endpoint_run_submissions",
        sa.Column(
            "endpoint_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("submission_num", sa.Integer(), nullable=False),
        sa.Column("submitted_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
            name=op.f("fk_endpoint_run_submissions_endpoint_id_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_endpoint_run_submissions_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "endpoint_id", "submission_num", name=op.f("pk_endpoint_run_submissions")
        ),
        sa.UniqueConstraint("run_id", name="uq_endpoint_run_submissions_run_id"),
    )
    with op.batch_alter_table("endpoint_run_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_endpoint_run_submissions_endpoint_id"), ["endpoint_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("endpoint_run_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_endpoint_run_submissions_endpoint_id"))

    op.drop_table("endpoint_run_submissions")

    with op.batch_alter_table("endpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_endpoints_status"))
        batch_op.drop_index(
            "ix_endpoints_pipeline_fetch_q",
        )

    op.drop_table("endpoints")
    # ### end Alembic commands ###
