"""Gateway scaling

Revision ID: f8336ffdac34
Revises: e9c5e7e26c78
Create Date: 2026-07-03 15:44:09.684229+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8336ffdac34"
down_revision = "e9c5e7e26c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scale_in", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(sa.Column("desired_replica_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("desired_replica_count")

    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.drop_column("scale_in")

    # ### end Alembic commands ###
