"""Add GatewayComputeModel.scale_in

Revision ID: dd83c131e78f
Revises: d35995d56249
Create Date: 2026-07-27 05:55:02.936913+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd83c131e78f"
down_revision = "d35995d56249"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scale_in", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.drop_column("scale_in")

    # ### end Alembic commands ###
