"""Add gateway scaling fields

Revision ID: d35995d56249
Revises: e9c5e7e26c78
Create Date: 2026-07-27 05:52:29.664340+00:00

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "d35995d56249"
down_revision = "e9c5e7e26c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(sa.Column("desired_replica_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("replica_scale_attempt", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_replica_scale_attempt_at",
                dstack._internal.server.models.NaiveDateTime(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_update_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("last_update_at")
        batch_op.drop_column("last_replica_scale_attempt_at")
        batch_op.drop_column("replica_scale_attempt")
        batch_op.drop_column("desired_replica_count")

    # ### end Alembic commands ###
