"""Add GatewayModel.hostname and backend_data

Revision ID: ecc9e8a0bfac
Revises: dd83c131e78f
Create Date: 2026-07-22 19:53:45.438752+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecc9e8a0bfac"
down_revision = "dd83c131e78f"
branch_labels = None
depends_on = None

# Partial table definitions for queries
gateways = sa.table(
    "gateways",
    sa.column("id"),
    sa.column("gateway_compute_id"),
    sa.column("hostname", sa.String(255)),
    sa.column("backend_data", sa.Text()),
)
gateway_computes = sa.table(
    "gateway_computes",
    sa.column("id"),
    sa.column("gateway_id"),
    sa.column("hostname", sa.String(100)),
    sa.column("backend_data", sa.Text()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hostname", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("backend_data", sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # Backfill from gateway_computes.
    # Only for AWS ACM gateways, as indicated by `hostname` being present.
    related_compute_with_hostname_filter = sa.and_(
        gateway_computes.c.hostname.is_not(None),
        sa.or_(
            gateway_computes.c.gateway_id == gateways.c.id,
            gateway_computes.c.id == gateways.c.gateway_compute_id,
        ),
    )
    op.execute(
        sa.update(gateways)
        .where(
            sa.select(gateway_computes.c.id).where(related_compute_with_hostname_filter).exists()
        )
        .values(
            hostname=(
                sa.select(gateway_computes.c.hostname)
                .where(related_compute_with_hostname_filter)
                .limit(1)
                .scalar_subquery()
            ),
            backend_data=(
                sa.select(gateway_computes.c.backend_data)
                .where(related_compute_with_hostname_filter)
                .limit(1)
                .scalar_subquery()
            ),
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("backend_data")
        batch_op.drop_column("hostname")

    # ### end Alembic commands ###
