"""Add EventTargetModel.entity_run_id

Revision ID: ad348ea93493
Revises: e9c5e7e26c78
Create Date: 2026-07-22 12:56:04.527041+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad348ea93493"
down_revision = "e9c5e7e26c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_targets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "entity_run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.create_index(
            batch_op.f("ix_event_targets_entity_run_id"), ["entity_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_event_targets_entity_run_id_runs"),
            "runs",
            ["entity_run_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_targets", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_event_targets_entity_run_id_runs"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_event_targets_entity_run_id"))
        batch_op.drop_column("entity_run_id")

    # ### end Alembic commands ###
