"""Gateway scaling retry

Revision ID: ea7a9287bf53
Revises: f8336ffdac34
Create Date: 2026-07-20 06:25:57.477538+00:00

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "ea7a9287bf53"
down_revision = "f8336ffdac34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("replica_scale_attempt", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_replica_scale_attempt_at",
                dstack._internal.server.models.NaiveDateTime(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_update_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateways", schema=None) as batch_op:
        batch_op.drop_column("last_update_at")
        batch_op.drop_column("last_replica_scale_attempt_at")
        batch_op.drop_column("replica_scale_attempt")

    # ### end Alembic commands ###
