"""Add JobModel.ready

Revision ID: 72cfa56364ad
Revises: a1c3f5e7b209
Create Date: 2026-08-04 07:02:02.041000+00:00

"""

import json
import uuid
from typing import Optional

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = "72cfa56364ad"
down_revision = "a1c3f5e7b209"
branch_labels = None
depends_on = None

# Partial table descriptions - only columns needed for the data migration below.
jobs_table = sa.Table(
    "jobs",
    sa.MetaData(),
    sa.Column("id", UUIDType(binary=False), primary_key=True, default=uuid.uuid4),
    sa.Column("run_id", UUIDType(binary=False)),
    sa.Column("status", sa.String(100)),
    sa.Column("registered", sa.Boolean()),
    sa.Column("ready", sa.Boolean()),
    sa.Column("job_spec_data", sa.Text()),
)
runs_table = sa.Table(
    "runs",
    sa.MetaData(),
    sa.Column("id", UUIDType(binary=False), primary_key=True, default=uuid.uuid4),
    sa.Column("run_spec", sa.Text()),
    sa.Column("service_spec", sa.Text(), nullable=True),
)


def _get_router_group_name(run_spec_data: str) -> Optional[str]:
    configuration = json.loads(run_spec_data).get("configuration") or {}
    if configuration.get("type") != "service":
        return None
    replica_groups = configuration.get("replicas")
    if not isinstance(replica_groups, list):
        return None
    for group in replica_groups:
        if isinstance(group, dict) and group.get("router") is not None:
            return group.get("name")
    return None


def _get_job_replica_group(job_spec_data: str) -> str:
    return json.loads(job_spec_data).get("replica_group", "0")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ready", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###

    bind = op.get_bind()

    # backfill ready=True for existing registered replicas

    bind.execute(jobs_table.update().where(jobs_table.c.registered == True).values(ready=True))

    # set registered=False for non-router replicas in services with a router

    candidate_jobs = bind.execute(
        sa.select(jobs_table.c.id, jobs_table.c.run_id, jobs_table.c.job_spec_data)
        .select_from(jobs_table.join(runs_table, jobs_table.c.run_id == runs_table.c.id))
        .where(
            jobs_table.c.registered == True,
            jobs_table.c.status == "RUNNING",
            runs_table.c.service_spec.is_not(None),
            sa.or_(
                runs_table.c.run_spec.like('%"sglang"%'),
                runs_table.c.run_spec.like('%"dynamo"%'),
            ),
        )
    ).all()

    run_ids = {row.run_id for row in candidate_jobs}
    router_group_name_by_run_id = {}
    if run_ids:
        for row in bind.execute(
            sa.select(runs_table.c.id, runs_table.c.run_spec).where(runs_table.c.id.in_(run_ids))
        ).all():
            router_group_name_by_run_id[row.id] = _get_router_group_name(row.run_spec)

    non_router_job_ids = []
    for row in candidate_jobs:
        router_group_name = router_group_name_by_run_id.get(row.run_id)
        if router_group_name is None:
            continue
        if _get_job_replica_group(row.job_spec_data) != router_group_name:
            non_router_job_ids.append(row.id)

    if non_router_job_ids:
        bind.execute(
            jobs_table.update()
            .where(jobs_table.c.id.in_(non_router_job_ids))
            .values(registered=False)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("ready")

    # ### end Alembic commands ###
