"""Require GatewayReplicaModel.backend_id

Revision ID: eee3e79f29e9
Revises: 04126c7ea0c8
Create Date: 2026-08-18 10:51:19.731160+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "eee3e79f29e9"
down_revision = "04126c7ea0c8"
branch_labels = None
depends_on = None

# partial definition for queries
gateway_computes = sa.table(
    "gateway_computes",
    sa.column("id"),
    sa.column("backend_id"),
)


def upgrade() -> None:
    # Gateway computes with backend_id=None were only possible in dstack Sky and were already
    # removed from all significant environments before this migration. So this cleanup query is
    # expected to be a NOOP in most cases, except for, possibly, some local dev databases.
    op.execute(sa.delete(gateway_computes).where(gateway_computes.c.backend_id.is_(None)))

    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.alter_column(
            "backend_id",
            existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.alter_column(
            "backend_id",
            existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        )

    # ### end Alembic commands ###
