"""Add GatewayReplicaModel.skip_min_processing_interval

Revision ID: 04126c7ea0c8
Revises: 3d4f69210528
Create Date: 2026-08-18 17:58:33.045050+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04126c7ea0c8"
down_revision = "3d4f69210528"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skip_min_processing_interval",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.drop_column("skip_min_processing_interval")
    # ### end Alembic commands ###
