"""Add ServiceRegistrationModel and ServiceReplicaRegistrationModel

Revision ID: 3d4f69210528
Revises: 72cfa56364ad
Create Date: 2026-08-13 00:52:02.969244+00:00

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d4f69210528"
down_revision = "72cfa56364ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_registrations",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("run_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "gateway_replica_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("register_attempt", sa.Integer(), nullable=False),
        sa.Column("register_status_message", sa.Text(), nullable=True),
        sa.Column("unregister_attempt", sa.Integer(), nullable=False),
        sa.Column("unregister_status_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gateway_replica_id"],
            ["gateway_computes.id"],
            name=op.f("fk_service_registrations_gateway_replica_id_gateway_computes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_service_registrations_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_registrations")),
        sa.UniqueConstraint(
            "run_id",
            "gateway_replica_id",
            name="uq_service_registrations_run_id_gateway_replica_id",
        ),
    )
    with op.batch_alter_table("service_registrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_registrations_gateway_replica_id"),
            ["gateway_replica_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_registrations_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "service_replica_registrations",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("job_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "gateway_replica_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("register_attempt", sa.Integer(), nullable=False),
        sa.Column("register_status_message", sa.Text(), nullable=True),
        sa.Column("unregister_attempt", sa.Integer(), nullable=False),
        sa.Column("unregister_status_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gateway_replica_id"],
            ["gateway_computes.id"],
            name=op.f("fk_service_replica_registrations_gateway_replica_id_gateway_computes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_service_replica_registrations_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_replica_registrations")),
        sa.UniqueConstraint(
            "job_id",
            "gateway_replica_id",
            name="uq_service_replica_registrations_job_id_gateway_replica_id",
        ),
    )
    with op.batch_alter_table("service_replica_registrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_replica_registrations_gateway_replica_id"),
            ["gateway_replica_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_replica_registrations_job_id"), ["job_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_replica_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_replica_registrations_job_id"))
        batch_op.drop_index(batch_op.f("ix_service_replica_registrations_gateway_replica_id"))

    op.drop_table("service_replica_registrations")
    with op.batch_alter_table("service_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_registrations_run_id"))
        batch_op.drop_index(batch_op.f("ix_service_registrations_gateway_replica_id"))

    op.drop_table("service_registrations")
    # ### end Alembic commands ###
