"""Add GatewayReplicaModel.name

Revision ID: dbbe9f32ec66
Revises: eee3e79f29e9
Create Date: 2026-08-20 19:40:13.516516+00:00

"""

import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = "dbbe9f32ec66"
down_revision = "eee3e79f29e9"
branch_labels = None
depends_on = None

# Partial table descriptions - only columns needed for the data migration below.
gateway_computes_table = sa.Table(
    "gateway_computes",
    sa.MetaData(),
    sa.Column("id", UUIDType(binary=False), primary_key=True, default=uuid.uuid4),
    sa.Column("name", sa.String(100)),
    sa.Column("gateway_id", UUIDType(binary=False), nullable=True),
    sa.Column("replica_num", sa.Integer()),
)
gateways_table = sa.Table(
    "gateways",
    sa.MetaData(),
    sa.Column("id", UUIDType(binary=False), primary_key=True, default=uuid.uuid4),
    sa.Column("name", sa.String(100)),
    sa.Column("gateway_compute_id", UUIDType(binary=False), nullable=True),
)


def upgrade() -> None:
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=100), nullable=True))

    bind = op.get_bind()
    gateway_name = sa.func.coalesce(
        sa.select(gateways_table.c.name)
        .where(
            sa.or_(
                gateways_table.c.id == gateway_computes_table.c.gateway_id,
                gateways_table.c.gateway_compute_id == gateway_computes_table.c.id,
            )
        )
        .scalar_subquery(),
        "unknown",  # fallback for deleted gateways
    )
    bind.execute(
        gateway_computes_table.update().values(
            name=gateway_name.concat("-").concat(
                sa.cast(gateway_computes_table.c.replica_num, sa.String)
            )
        )
    )

    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.String(length=100), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gateway_computes", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
