type: dev-environment
name: axolotl-vscode

# Using the official Axolotl's Docker image
image: winglian/axolotl-cloud:main-20240429-py3.11-cu121-2.2.1

# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN
  - WANDB_API_KEY

ide: vscode

# Use either spot or on-demand instances
spot_policy: auto

resources:
  # Two or more 24GB GPUs (required by FSDP)
  gpu: 24GB:2..