package shim

import (
	"context"
	"encoding/hex"
	"errors"
	"math/rand"
	"os"
	"os/user"
	"path/filepath"
	"strconv"
	"sync"
	"testing"
	"time"

	dockertypes "github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	docker "github.com/docker/docker/client"
	"github.com/dstackai/dstack/runner/internal/common/consts"
	"github.com/dstackai/dstack/runner/internal/common/gpu"
	"github.com/dstackai/dstack/runner/internal/common/types"
	"github.com/dstackai/dstack/runner/internal/shim/host"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

/*
Docker tests are not parallel: they share the Docker daemon, and a DockerRunner adopts
every task container on the host, including the containers of the other tests.
*/

// TestDocker_SSHServer pulls ubuntu image (without sshd), installs openssh-server and exits
// Basically, it indirectly tests a shell script generated by getSSHShellCommands
func TestDocker_SSHServer(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands:         []string{"/usr/sbin/sshd -V 2>&1 | grep OpenSSH"},
		sshShellCommands: true,
		tasksDir:         t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	defer cleanupTask(t, dockerRunner, taskConfig.ID)

	assert.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	assert.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))
	assertTaskDone(t, dockerRunner, taskConfig.ID)
}

func TestDocker_ShmNoexecByDefault(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands: []string{"mount | grep '/dev/shm .*size=65536k' | grep noexec"},
		tasksDir: t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	defer cleanupTask(t, dockerRunner, taskConfig.ID)

	assert.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	assert.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))
	assertTaskDone(t, dockerRunner, taskConfig.ID)
}

func TestDocker_ShmExecIfSizeSpecified(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands: []string{"mount | grep '/dev/shm .*size=1024k' | grep -v noexec"},
		tasksDir: t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	taskConfig.ShmSize = 1024 * 1024
	defer cleanupTask(t, dockerRunner, taskConfig.ID)

	assert.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	assert.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))
	assertTaskDone(t, dockerRunner, taskConfig.ID)
}

func TestDocker_ContainerExitedWithError(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands: []string{"echo failed for a reason", "exit 3"},
		tasksDir: t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	defer cleanupTask(t, dockerRunner, taskConfig.ID)

	require.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	require.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))

	taskInfo := waitTaskTerminated(t, dockerRunner, taskConfig.ID)
	assert.Equal(t, string(types.TerminationReasonContainerExitedWithError), taskInfo.TerminationReason)
	assert.Contains(t, taskInfo.TerminationMessage, "failed for a reason")
}

// TestDocker_RestoredTaskIsTerminated simulates a shim restart: since Start() does
// not wait for the container to exit, a task started by one runner must be terminated
// by another runner that restored it from the container
func TestDocker_RestoredTaskIsTerminated(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands: []string{"sleep 3", "exit 7"},
		tasksDir: t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	require.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	require.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))

	// The restarted shim restores the task from its container
	restartedRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)
	defer cleanupTask(t, restartedRunner, taskConfig.ID)
	require.Equal(t, taskConfig.ID, restartedRunner.TaskInfo(taskConfig.ID).ID)

	taskInfo := waitTaskTerminated(t, restartedRunner, taskConfig.ID)
	assert.Equal(t, string(types.TerminationReasonContainerExitedWithError), taskInfo.TerminationReason)
}

// TestDocker_RestoredTaskKeepsTerminationReason covers the task state file: why a task
// was terminated cannot be recovered from its container
func TestDocker_RestoredTaskKeepsTerminationReason(t *testing.T) {
	if testing.Short() {
		t.Skip()
	}

	params := &dockerParametersMock{
		commands: []string{"sleep 60"},
		tasksDir: t.TempDir(),
	}

	timeout := 180 // seconds
	ctx, cancel := context.WithTimeout(t.Context(), time.Duration(timeout)*time.Second)
	defer cancel()

	dockerRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)

	taskConfig := createTaskConfig(t)
	require.NoError(t, dockerRunner.Submit(ctx, taskConfig))
	require.NoError(t, dockerRunner.Start(ctx, taskConfig.ID))
	require.NoError(t, dockerRunner.Terminate(
		ctx, taskConfig.ID, 0, string(types.TerminationReasonTerminatedByUser), "bye",
	))

	// The restarted shim restores the task from its container and its state file
	restartedRunner, err := NewDockerRunner(ctx, params)
	require.NoError(t, err)
	defer cleanupTask(t, restartedRunner, taskConfig.ID)

	taskInfo := restartedRunner.TaskInfo(taskConfig.ID)
	assert.Equal(t, TaskStatusTerminated, taskInfo.Status)
	assert.Equal(t, string(types.TerminationReasonTerminatedByUser), taskInfo.TerminationReason)
	assert.Equal(t, "bye", taskInfo.TerminationMessage)
}

func TestVolumesFromMounts(t *testing.T) {
	mounts := []dockertypes.MountPoint{
		{Source: "/root/.dstack/runners/task-0-0-1234abcd/runner", Destination: consts.RunnerTempDir},
		{Source: "/mnt/disks/dstack-volumes/volume-1", Destination: "/volume"},
		{Source: "/home/dstack/data", Destination: "/instance-data"},
	}

	assert.Equal(t, []VolumeInfo{{Name: "volume-1"}}, volumesFromMounts(mounts))
	assert.Nil(t, volumesFromMounts(nil))
}

func TestConfigureGpus_Nvidia(t *testing.T) {
	containerConfig := &container.Config{}
	hostConfig := &container.HostConfig{}
	gpuIDs := []string{"GPU-beef", "GPU-cafe"}

	configureGpus(containerConfig, hostConfig, gpu.GpuVendorNvidia, gpuIDs, createContainerOptions{})

	require.Len(t, hostConfig.DeviceRequests, 1)
	assert.Equal(t, gpuIDs, hostConfig.DeviceRequests[0].DeviceIDs)
	assert.Equal(
		t,
		[][]string{nvidiaDeviceRequestCapabilities(createContainerOptions{})},
		hostConfig.DeviceRequests[0].Capabilities,
	)
	assert.Empty(t, containerConfig.Env)
}

func TestNvidiaDeviceRequestCapabilities(t *testing.T) {
	assert.Equal(
		t,
		[]string{"gpu", "utility", "compute", "graphics", "video", "display", "compat32"},
		nvidiaDeviceRequestCapabilities(createContainerOptions{}),
	)
	assert.Equal(
		t,
		[]string{"gpu", "utility", "compute", "graphics", "video", "compat32"},
		nvidiaDeviceRequestCapabilities(createContainerOptions{disableNvidiaDisplayCapability: true}),
	)
}

func TestShouldRetryWithoutNvidiaDisplayCapability(t *testing.T) {
	err := assert.AnError
	assert.False(t, shouldRetryWithoutNvidiaDisplayCapability(gpu.GpuVendorNvidia, err))

	err = errors.New("nvidia-container-cli: mount error: stat failed: /dev/nvidia-modeset")
	assert.True(t, shouldRetryWithoutNvidiaDisplayCapability(gpu.GpuVendorNvidia, err))
	assert.False(t, shouldRetryWithoutNvidiaDisplayCapability(gpu.GpuVendorAmd, err))
	assert.False(t, shouldRetryWithoutNvidiaDisplayCapability(gpu.GpuVendorNvidia, nil))
}

func TestMakeTaskDir(t *testing.T) {
	args := CLIArgs{}
	args.Shim.HomeDir = t.TempDir()

	taskDir, err := args.MakeTaskDir("task-0-0-1234abcd")
	require.NoError(t, err)

	assert.Equal(t, filepath.Join(args.Shim.HomeDir, "runners", "task-0-0-1234abcd"), taskDir)
	info, err := os.Stat(taskDir)
	require.NoError(t, err)
	// Shim's files in the task dir, e.g. the task state file, are not world-readable
	assert.Zero(t, info.Mode().Perm()&0o077, "task dir mode: %s", info.Mode())
	// Only the runner dir inside the task dir is shared with the container
	runnerDir := filepath.Join(taskDir, "runner")
	assert.DirExists(t, runnerDir)
	mounts, err := args.DockerMounts(taskDir)
	require.NoError(t, err)
	assert.Contains(t, mounts, mount.Mount{
		Type:   mount.TypeBind,
		Source: runnerDir,
		Target: consts.RunnerTempDir,
	})
}

/* Mocks */

type dockerParametersMock struct {
	commands         []string
	sshShellCommands bool
	// tasksDir is the parent dir of all task dirs
	tasksDir string
}

func (c *dockerParametersMock) DockerPrivileged() bool {
	return false
}

func (c *dockerParametersMock) DockerPJRTDevice() string {
	return ""
}

func (c *dockerParametersMock) DockerShellCommands(authorizedKeys []string, runnerHttpAddress string) []string {
	commands := make([]string, 0)
	if c.sshShellCommands {
		commands = append(commands, getSSHShellCommands()...)
	}
	commands = append(commands, c.commands...)
	return commands
}

func (c *dockerParametersMock) DockerPassEnv() []string {
	return []string{}
}

func (c *dockerParametersMock) DockerPorts() []int {
	return []int{}
}

func (c *dockerParametersMock) DockerMounts(hostTaskDir string) ([]mount.Mount, error) {
	return []mount.Mount{
		{Type: mount.TypeBind, Source: taskRunnerDir(hostTaskDir), Target: consts.RunnerTempDir},
	}, nil
}

func (c *dockerParametersMock) TasksDir() string {
	return c.tasksDir
}

func (c *dockerParametersMock) MakeTaskDir(name string) (string, error) {
	taskDir := filepath.Join(c.tasksDir, name)
	if err := os.MkdirAll(taskRunnerDir(taskDir), 0o755); err != nil {
		return "", err
	}
	return taskDir, nil
}

/* Utilities */

var (
	randSrc = rand.New(rand.NewSource(time.Now().UnixNano()))
	randMu  = sync.Mutex{}
)

func generateID(t *testing.T) string {
	const idLen = 16
	b := make([]byte, idLen/2)
	randMu.Lock()
	defer randMu.Unlock()
	_, err := randSrc.Read(b)
	require.Nil(t, err)
	return hex.EncodeToString(b)[:idLen]
}

// assertTaskDone waits until the task is terminated and asserts that its container
// exited successfully
func assertTaskDone(t *testing.T, runner *DockerRunner, taskID string) {
	t.Helper()
	taskInfo := waitTaskTerminated(t, runner, taskID)
	assert.Equal(t, string(types.TerminationReasonDoneByRunner), taskInfo.TerminationReason)
	assert.Empty(t, taskInfo.TerminationMessage)
}

// waitTaskTerminated processes tasks until the task is terminated, as Start() only
// starts the container and does not wait for it to exit.
// The timeout covers the whole container lifetime, which may be long, e.g., if the
// container installs packages
func waitTaskTerminated(t *testing.T, runner *DockerRunner, taskID string) TaskInfo {
	t.Helper()
	require.Eventually(t, func() bool {
		runner.ProcessTasks(t.Context())
		return runner.TaskInfo(taskID).Status == TaskStatusTerminated
	}, 150*time.Second, 200*time.Millisecond)
	// Read outside of the condition, which Eventually runs in a separate goroutine
	// that may outlive the call
	return runner.TaskInfo(taskID)
}

// cleanupTask terminates and removes the task, so that its container does not outlive
// the test even if the test fails. A container left behind is adopted by the runners of
// the following test runs, breaking them in confusing ways
func cleanupTask(t *testing.T, runner *DockerRunner, taskID string) {
	t.Helper()
	reason := string(types.TerminationReasonTerminatedByUser)
	if err := runner.Terminate(t.Context(), taskID, 0, reason, "test cleanup"); err != nil {
		t.Logf("failed to terminate task %s: %s", taskID, err)
	}
	if err := runner.Remove(t.Context(), taskID); err != nil {
		t.Logf("failed to remove task %s: %s", taskID, err)
	}
}

func createTaskConfig(t *testing.T) TaskConfig {
	return TaskConfig{
		ID:        generateID(t),
		Name:      t.Name(),
		ImageName: "ubuntu",
	}
}

func pullMsg(id, status string, current, total uint64) PullMessage {
	m := PullMessage{Id: id, Status: status}
	m.ProgressDetail.Current = current
	m.ProgressDetail.Total = total
	return m
}

func TestPullTracker_Empty(t *testing.T) {
	tracker := newPullTracker()
	assert.Nil(t, tracker.Progress())
}

func TestPullTracker_AlreadyExists(t *testing.T) {
	tracker := newPullTracker()
	tracker.Update(PullMessage{Id: "3.11", Status: "Pulling from library/python"})
	for _, id := range []string{"aaa", "bbb", "ccc"} {
		tracker.Update(PullMessage{Id: id, Status: "Already exists"})
	}
	tracker.Update(PullMessage{Status: "Digest: sha256:***"})
	tracker.Update(PullMessage{Status: "Status: Image is up to date for python:3.11"})
	p := tracker.Progress()
	require.NotNil(t, p)
	assert.Equal(t, uint64(0), p.DownloadedBytes)
	assert.Equal(t, uint64(0), p.ExtractedBytes)
	assert.Equal(t, uint64(0), p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)
}

func TestPullTracker_FullPull(t *testing.T) {
	const sizeA, sizeB uint64 = 111, 222

	tracker := newPullTracker()
	tracker.Update(PullMessage{Id: "3.11", Status: "Pulling from library/python"})
	tracker.Update(PullMessage{Id: "aaa", Status: "Pulling fs layer"})
	tracker.Update(PullMessage{Id: "bbb", Status: "Pulling fs layer"})
	tracker.Update(PullMessage{Id: "aaa", Status: "Waiting"})
	tracker.Update(PullMessage{Id: "bbb", Status: "Waiting"})

	// Layers announced but sizes unknown yet
	p := tracker.Progress()
	require.NotNil(t, p)
	assert.Equal(t, uint64(0), p.DownloadedBytes)
	assert.Equal(t, uint64(0), p.ExtractedBytes)
	assert.Equal(t, uint64(0), p.TotalBytes)
	assert.False(t, p.IsTotalBytesFinal)

	// Both layers start downloading - sizes now known
	tracker.Update(pullMsg("aaa", "Downloading", 100, sizeA))
	tracker.Update(pullMsg("bbb", "Downloading", 200, sizeB))

	p = tracker.Progress()
	assert.Equal(t, uint64(300), p.DownloadedBytes)
	assert.Equal(t, uint64(0), p.ExtractedBytes)
	assert.Equal(t, sizeA+sizeB, p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)

	// Downloads complete
	tracker.Update(pullMsg("aaa", "Downloading", sizeA, sizeA))
	tracker.Update(PullMessage{Id: "aaa", Status: "Download complete"})
	tracker.Update(pullMsg("bbb", "Downloading", sizeB, sizeB))
	tracker.Update(PullMessage{Id: "bbb", Status: "Download complete"})

	p = tracker.Progress()
	assert.Equal(t, sizeA+sizeB, p.DownloadedBytes)
	assert.Equal(t, uint64(0), p.ExtractedBytes)
	assert.Equal(t, sizeA+sizeB, p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)

	// Both layers start extracting
	tracker.Update(pullMsg("aaa", "Extracting", 100, sizeA))
	tracker.Update(pullMsg("bbb", "Extracting", 200, sizeB))

	p = tracker.Progress()
	assert.Equal(t, sizeA+sizeB, p.DownloadedBytes)
	assert.Equal(t, uint64(300), p.ExtractedBytes)
	assert.Equal(t, sizeA+sizeB, p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)

	// Extractions complete
	tracker.Update(pullMsg("aaa", "Extracting", sizeA, sizeA))
	tracker.Update(PullMessage{Id: "aaa", Status: "Pull complete"})
	tracker.Update(pullMsg("bbb", "Extracting", sizeB, sizeB))
	tracker.Update(PullMessage{Id: "bbb", Status: "Pull complete"})
	tracker.Update(PullMessage{Status: "Digest: sha256:***"})
	tracker.Update(PullMessage{Status: "Status: Downloaded newer image for python:3.11"})

	p = tracker.Progress()
	assert.Equal(t, sizeA+sizeB, p.DownloadedBytes)
	assert.Equal(t, sizeA+sizeB, p.ExtractedBytes)
	assert.Equal(t, sizeA+sizeB, p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)
}

func TestPullTracker_MixedLayerStatuses(t *testing.T) {
	tracker := newPullTracker()

	tracker.Update(PullMessage{Id: "layer-exists", Status: "Already exists"})
	tracker.Update(pullMsg("layer-downloading", "Downloading", 50, 100))
	tracker.Update(pullMsg("layer-extracting", "Extracting", 100, 200))
	tracker.Update(PullMessage{Id: "layer-waiting", Status: "Waiting"})

	p := tracker.Progress()
	require.NotNil(t, p)
	assert.Equal(t, uint64(50+200), p.DownloadedBytes)
	assert.Equal(t, uint64(100), p.ExtractedBytes)
	assert.Equal(t, uint64(100+200), p.TotalBytes)
	assert.False(t, p.IsTotalBytesFinal) // layer-waiting size unknown
}

func TestPullTracker_NonBytesExtractingUnit(t *testing.T) {
	tracker := newPullTracker()
	tracker.Update(PullMessage{Id: "3.11", Status: "Pulling from library/python"})
	tracker.Update(PullMessage{Id: "aaa", Status: "Pulling fs layer"})
	tracker.Update(pullMsg("aaa", "Downloading", 100, 200))
	tracker.Update(pullMsg("aaa", "Downloading", 200, 200))
	tracker.Update(PullMessage{Id: "aaa", Status: "Download complete"})
	// Newer Docker daemons report extraction progress in seconds. Tested with 29.5.2
	tracker.Update(PullMessage{Id: "aaa", Status: "Extracting", ProgressDetail: ProgressDetail{Current: 1, Units: "s"}})
	tracker.Update(PullMessage{Id: "aaa", Status: "Extracting", ProgressDetail: ProgressDetail{Current: 2, Units: "s"}})

	p := tracker.Progress()
	require.NotNil(t, p)
	assert.Equal(t, uint64(200), p.DownloadedBytes)
	assert.Equal(t, uint64(0), p.ExtractedBytes) // reported in seconds, bytes unknown
	assert.Equal(t, uint64(200), p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)

	tracker.Update(PullMessage{Id: "aaa", Status: "Pull complete"})

	p = tracker.Progress()
	require.NotNil(t, p)
	assert.Equal(t, uint64(200), p.DownloadedBytes)
	assert.Equal(t, uint64(200), p.ExtractedBytes) // pull complete => extracted == total
	assert.Equal(t, uint64(200), p.TotalBytes)
	assert.True(t, p.IsTotalBytesFinal)
}

/* restoreStateFromContainers */

// restoreClientMock implements the only two docker.APIClient methods used by
// restoreStateFromContainers, letting it run without a Docker daemon.
// Any other method panics with a nil pointer dereference, which is intentional:
// this mock must be updated if restoreStateFromContainers starts using them
type restoreClientMock struct {
	docker.APIClient
	containers []dockertypes.Container
	inspect    map[string]dockertypes.ContainerJSON
}

func (c *restoreClientMock) ContainerList(
	context.Context, container.ListOptions,
) ([]dockertypes.Container, error) {
	return c.containers, nil
}

func (c *restoreClientMock) ContainerInspect(
	_ context.Context, containerID string,
) (dockertypes.ContainerJSON, error) {
	return c.inspect[containerID], nil
}

// nvidiaContainer returns a task container summary and its inspection response
// with the given GPU IDs requested
func nvidiaContainer(containerID, taskID string, gpuIDs []string) (dockertypes.Container, dockertypes.ContainerJSON) {
	summary := dockertypes.Container{
		ID:     containerID,
		Names:  []string{"/" + containerID},
		State:  containerStateRunning,
		Labels: map[string]string{LabelKeyIsTask: LabelValueTrue, LabelKeyTaskID: taskID},
		Mounts: []dockertypes.MountPoint{
			{Destination: consts.RunnerTempDir, Source: "/root/.dstack/runners/" + containerID + "/runner"},
		},
	}
	inspection := dockertypes.ContainerJSON{
		ContainerJSONBase: &dockertypes.ContainerJSONBase{
			HostConfig: &container.HostConfig{
				Resources: container.Resources{
					DeviceRequests: []container.DeviceRequest{{DeviceIDs: gpuIDs}},
				},
			},
		},
		Config:          &container.Config{},
		NetworkSettings: &dockertypes.NetworkSettings{},
	}
	return summary, inspection
}

func newRestoreRunner(t *testing.T, gpuIDs []string, containers ...dockertypes.Container) *DockerRunner {
	t.Helper()
	gpus := make([]host.GpuInfo, 0, len(gpuIDs))
	for _, id := range gpuIDs {
		gpus = append(gpus, host.GpuInfo{Vendor: gpu.GpuVendorNvidia, ID: id})
	}
	gpuLock, err := NewGpuLock(gpus)
	require.NoError(t, err)
	return &DockerRunner{
		client:       &restoreClientMock{containers: containers, inspect: map[string]dockertypes.ContainerJSON{}},
		dockerParams: &dockerParametersMock{tasksDir: t.TempDir()},
		gpuVendor:    gpu.GpuVendorNvidia,
		gpuLock:      gpuLock,
		tasks:        NewTaskStorage(),
		userLookup:   failingUserLookup,
	}
}

// TestRestoreState_FromStateFile checks that the task dir and the part of the task
// state that cannot be recovered from the container are restored from the state file
func TestRestoreState_FromStateFile(t *testing.T) {
	containerShort, containerFull := nvidiaContainer("container-1", "task-1", nil)
	runner := newRestoreRunner(t, nil, containerShort)
	runner.client.(*restoreClientMock).inspect["container-1"] = containerFull
	tasksDir := runner.dockerParams.TasksDir()
	taskDir := filepath.Join(tasksDir, "container-1")
	require.NoError(t, os.MkdirAll(taskRunnerDir(taskDir), 0o755))
	task := NewTaskFromConfig(TaskConfig{
		ID:          "task-1",
		Name:        "task",
		HostSshUser: "root",
		HostSshKeys: []string{"ssh-ed25519 AAAA"},
	})
	task.SetStatusTerminated(string(types.TerminationReasonTerminatedByUser), "bye")
	require.NoError(t, writeTaskState(taskDir, newTaskState(&task)))

	stored := scanTaskDirs(t.Context(), tasksDir)
	require.NoError(t, runner.restoreStateFromContainers(t.Context(), stored))

	restored, ok := runner.tasks.Get("task-1")
	require.True(t, ok)
	assert.Equal(t, taskDir, restored.taskDir)
	assert.Equal(t, TaskStatusTerminated, restored.Status)
	assert.Equal(t, string(types.TerminationReasonTerminatedByUser), restored.TerminationReason)
	assert.Equal(t, "bye", restored.TerminationMessage)
	// The host SSH keys are only known to the state file
	assert.Equal(t, []string{"ssh-ed25519 AAAA"}, restored.config.HostSshKeys)
}

// TestRestoreState_LegacyTaskDir checks that a task started by a shim version that did
// not write state files is restored with its dir, named after the container, so that the
// dir is still removed along with the task
func TestRestoreState_LegacyTaskDir(t *testing.T) {
	containerShort, containerFull := nvidiaContainer("container-1", "task-1", nil)
	containerShort.Mounts = append(containerShort.Mounts, dockertypes.MountPoint{
		Source: volumeMountPointDir + "/volume-1", Destination: "/volume",
	})
	runner := newRestoreRunner(t, nil, containerShort)
	runner.client.(*restoreClientMock).inspect["container-1"] = containerFull
	legacyDir := filepath.Join(runner.dockerParams.TasksDir(), "container-1")
	require.NoError(t, os.MkdirAll(legacyDir, 0o755))

	require.NoError(t, runner.restoreStateFromContainers(t.Context(), nil))

	restored, ok := runner.tasks.Get("task-1")
	require.True(t, ok)
	assert.Equal(t, legacyDir, restored.taskDir)
	assert.Equal(t, TaskStatusRunning, restored.Status)
	// Without a state file, the volumes are recovered from the container mounts
	assert.Equal(t, []VolumeInfo{{Name: "volume-1"}}, restored.config.Volumes)
}

// TestRestoreState_NoTaskDir checks that a task whose dir is gone is still restored
func TestRestoreState_NoTaskDir(t *testing.T) {
	containerShort, containerFull := nvidiaContainer("container-1", "task-1", nil)
	runner := newRestoreRunner(t, nil, containerShort)
	runner.client.(*restoreClientMock).inspect["container-1"] = containerFull

	require.NoError(t, runner.restoreStateFromContainers(t.Context(), nil))

	restored, ok := runner.tasks.Get("task-1")
	require.True(t, ok)
	assert.Empty(t, restored.taskDir)
}

// TestRestoreState_GpuLockedByAnotherTaskIsNotOwned checks that a task restored with
// a GPU already locked by another restored task does not claim that GPU, so that
// releasing the task's resources does not release a GPU still in use
func TestRestoreState_GpuLockedByAnotherTaskIsNotOwned(t *testing.T) {
	firstShort, firstFull := nvidiaContainer("container-1", "task-1", []string{"GPU-beef"})
	// Should not happen, but if it does, the second task must not take over the GPU
	secondShort, secondFull := nvidiaContainer("container-2", "task-2", []string{"GPU-beef", "GPU-f00d"})
	runner := newRestoreRunner(t, []string{"GPU-beef", "GPU-f00d"}, firstShort, secondShort)
	mock := runner.client.(*restoreClientMock)
	mock.inspect["container-1"] = firstFull
	mock.inspect["container-2"] = secondFull

	require.NoError(t, runner.restoreStateFromContainers(t.Context(), nil))

	firstTask, ok := runner.tasks.Get("task-1")
	require.True(t, ok)
	assert.Equal(t, []string{"GPU-beef"}, firstTask.gpuIDs)
	secondTask, ok := runner.tasks.Get("task-2")
	require.True(t, ok)
	assert.Equal(t, []string{"GPU-f00d"}, secondTask.gpuIDs, "GPU-beef is owned by task-1")

	// Releasing the second task must not free the GPU owned by the first one
	runner.gpuLock.Release(t.Context(), secondTask.gpuIDs)
	assert.True(t, runner.gpuLock.lock["GPU-beef"], "GPU-beef")
	assert.False(t, runner.gpuLock.lock["GPU-f00d"], "GPU-f00d")
}

// TestRestoreState_DuplicateTaskReleasesGpus checks that the GPUs locked for a task
// that cannot be stored are released, as nothing else will release them
func TestRestoreState_DuplicateTaskReleasesGpus(t *testing.T) {
	firstShort, firstFull := nvidiaContainer("container-1", "task-1", []string{"GPU-beef"})
	// Two containers reporting the same task ID: the second one is not stored
	secondShort, secondFull := nvidiaContainer("container-2", "task-1", []string{"GPU-f00d"})
	runner := newRestoreRunner(t, []string{"GPU-beef", "GPU-f00d"}, firstShort, secondShort)
	mock := runner.client.(*restoreClientMock)
	mock.inspect["container-1"] = firstFull
	mock.inspect["container-2"] = secondFull

	require.NoError(t, runner.restoreStateFromContainers(t.Context(), nil))

	assert.Len(t, runner.tasks.List(), 1)
	assert.True(t, runner.gpuLock.lock["GPU-beef"], "GPU-beef")
	assert.False(t, runner.gpuLock.lock["GPU-f00d"], "GPU-f00d is not owned by any task")
}

const testHostSshUser = "test_user"

// newHostSshKeysRunner returns a runner whose host user's home is a temp dir, along with
// the path of that user's authorized_keys file. The mocked lookup reports the ids of the
// current process, so that setting the ownership of the file succeeds without root
func newHostSshKeysRunner(t *testing.T) (*DockerRunner, string) {
	t.Helper()
	usr := &user.User{
		Username: testHostSshUser,
		HomeDir:  t.TempDir(),
		Uid:      strconv.Itoa(os.Getuid()),
		Gid:      strconv.Itoa(os.Getgid()),
	}
	runner := newTestRunner(t, nil)
	runner.userLookup = func(username string) (*user.User, error) {
		if username != usr.Username {
			return nil, errors.New("user not found")
		}
		return usr, nil
	}
	return runner, authorizedKeysPath(usr.HomeDir)
}

func addHostSshKeysTask(t *testing.T, runner *DockerRunner, taskID string, keys ...string) Task {
	t.Helper()
	task := NewTaskFromConfig(TaskConfig{
		ID:          taskID,
		Name:        taskID,
		HostSshUser: testHostSshUser,
		HostSshKeys: keys,
	})
	require.True(t, runner.tasks.Add(task))
	return task
}

func cleanupHostSshKeysTask(t *testing.T, runner *DockerRunner, task *Task) {
	t.Helper()
	task.Lock(t.Context())
	defer task.Release(t.Context())
	runner.cleanupLocked(t.Context(), task)
}

func readAuthorizedKeysFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(content)
}

// TestHostSshKeys_CoLocatedTasksShareKey covers dstackai/dstack#4174: on an instance with
// blocks, the tasks co-located on it hold the same host SSH key, and the first one to
// finish must not revoke the access of the others
func TestHostSshKeys_CoLocatedTasksShareKey(t *testing.T) {
	const key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGYzO2yHhoIzYHnGH5CT/hpTNGRHvJHkKQlXqPZ0Uxwj user@host"
	entry := key + " # added by dstack-shim\n"
	runner, keysPath := newHostSshKeysRunner(t)
	first := addHostSshKeysTask(t, runner, "task-1", key)
	second := addHostSshKeysTask(t, runner, "task-2", key)

	require.NoError(t, runner.reconcileHostSshKeys(t.Context()))
	// One entry, however many tasks are using the key
	assert.Equal(t, entry, readAuthorizedKeysFile(t, keysPath))

	cleanupHostSshKeysTask(t, runner, &first)
	assert.Equal(t, entry, readAuthorizedKeysFile(t, keysPath), "the key is still used by task-2")

	cleanupHostSshKeysTask(t, runner, &second)
	assert.Empty(t, readAuthorizedKeysFile(t, keysPath), "the last task using the key is gone")
}

// TestHostSshKeys_KeepsKeyAddedByHand checks that a key the user added to the file
// themselves survives a task that happened to use the same key
func TestHostSshKeys_KeepsKeyAddedByHand(t *testing.T) {
	const key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGYzO2yHhoIzYHnGH5CT/hpTNGRHvJHkKQlXqPZ0Uxwj user@host"
	runner, keysPath := newHostSshKeysRunner(t)
	writeTestAuthorizedKeys(t, keysPath, key+"\n")
	task := addHostSshKeysTask(t, runner, "task-1", key)

	require.NoError(t, runner.reconcileHostSshKeys(t.Context()))
	assert.Equal(t, key+"\n"+key+" # added by dstack-shim\n", readAuthorizedKeysFile(t, keysPath))

	cleanupHostSshKeysTask(t, runner, &task)
	assert.Equal(t, key+"\n", readAuthorizedKeysFile(t, keysPath))
}

// TestHostSshKeys_SweepOrphanedTaskDir checks that the keys of a task that has no
// container are removed, while the keys of a task that has one are kept
func TestHostSshKeys_SweepOrphanedTaskDir(t *testing.T) {
	const (
		liveKey    = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGYzO2yHhoIzYHnGH5CT/hpTNGRHvJHkKQlXqPZ0Uxwj live"
		orphanKey  = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILuLmyPGV/gcatBaZFxRPKGQVJ4vBjuqEsHIkKGrGZKS orphan"
		markerLine = " # added by dstack-shim\n"
	)
	runner, keysPath := newHostSshKeysRunner(t)
	addHostSshKeysTask(t, runner, "task-1", liveKey)
	orphan := NewTaskFromConfig(TaskConfig{
		ID:          "task-2",
		Name:        "task-2",
		HostSshUser: testHostSshUser,
		HostSshKeys: []string{orphanKey},
	})
	orphanDir := filepath.Join(runner.dockerParams.TasksDir(), "task-2")
	require.NoError(t, os.MkdirAll(orphanDir, 0o755))
	require.NoError(t, writeTaskState(orphanDir, newTaskState(&orphan)))
	stored := scanTaskDirs(t.Context(), runner.dockerParams.TasksDir())
	// Both tasks left their keys behind before the shim restarted
	writeTestAuthorizedKeys(t, keysPath, liveKey+markerLine+orphanKey+markerLine)

	runner.sweepOrphanedTaskDirs(t.Context(), stored)

	assert.Equal(t, liveKey+markerLine, readAuthorizedKeysFile(t, keysPath))
	assert.NoDirExists(t, orphanDir)
}
