type: dev-environment
# The name is optional, if not specified, generated randomly
name: ah-vscode

# If `image` is not specified, dstack uses its default image
python: "3.10"

# Required environment variables
env:
  - HF_TOKEN
  - ACCELERATE_LOG_LEVEL=info
  - WANDB_API_KEY

# Uncomment if you want the environment to be pre-installed
#init:
#  - conda install cuda
#  - git clone https://github.com/huggingface/alignment-handbook.git
#  - cd alignment-handbook
#  - pip install .
#  - pip install flash-attn --no-build-isolation
#  - pip install wandb

ide: vscode

# Uncomment to leverage spot instances
#spot_policy: auto

resources:
  gpu:
    # 24GB or more VRAM
    memory: 24GB..
    # One or more GPU
    count: 1..
