type: task

python: "3.11"

nodes: 3

env:
  - FT_MODEL_CONFIG_PATH
  - ACCEL_CONFIG_PATH

  - HUGGING_FACE_HUB_TOKEN
  - WANDB_API_KEY

commands:
  - conda install cuda
  - git clone https://github.com/huggingface/alignment-handbook.git
  - mkdir -p alignment-handbook/recipes/custom/
  - cp "$FT_MODEL_CONFIG_PATH" alignment-handbook/recipes/custom/config.yaml
  - cp "$ACCEL_CONFIG_PATH" alignment-handbook/recipes/custom/accel_config.yaml

  - cd alignment-handbook
  - python -m pip -q install .
  - python -m pip install -q flash-attn --no-build-isolation

  - pip install -q wandb
  - wandb login $WANDB_API_KEY

  - ACCELERATE_LOG_LEVEL=info accelerate launch 
      --config_file examples/fine-tuning/alignment-handbook/fsdp_qlora_full_shard.yaml \
      --main_process_ip=$DSTACK_MASTER_NODE_IP
      --main_process_port=8008
      --machine_rank=$DSTACK_NODE_RANK
      --num_processes=$DSTACK_GPUS_NUM
      --num_machines=$DSTACK_NODES_NUM
      scripts/run_sft.py recipes/custom/config.yaml
ports:
  - 6006
  
resources:
  gpu: 24GB:2
  shm_size: 24GB