"""Add JobModel.volumes_detached_at

Revision ID: da574e93fee0
Revises: ffa99edd1988
Create Date: 2025-01-29 11:52:26.941513

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "da574e93fee0"
down_revision = "ffa99edd1988"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "volumes_detached_at",
                dstack._internal.server.models.NaiveDateTime(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("volumes_detached_at")

    # ### end Alembic commands ###
