"""Move attachment_data to volumes_attachments

Revision ID: a751ef183f27
Revises: 1e76fb0dde87
Create Date: 2025-02-12 13:19:57.569591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a751ef183f27"
down_revision = "1e76fb0dde87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes_attachments", schema=None) as batch_op:
        batch_op.alter_column("instace_id", new_column_name="instance_id")
        batch_op.add_column(sa.Column("attachment_data", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes_attachments", schema=None) as batch_op:
        batch_op.drop_column("attachment_data")
        batch_op.alter_column("instance_id", new_column_name="instace_id")

    # ### end Alembic commands ###
