"""Add RunModel.resubmission_attempt

Revision ID: 7ba3b59d7ca6
Revises: 7bc2586e8b9e
Create Date: 2025-04-15 18:00:35.320906

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ba3b59d7ca6"
down_revision = "7bc2586e8b9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resubmission_attempt", sa.Integer(), nullable=True))
    batch_op.execute("UPDATE runs SET resubmission_attempt = 0")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.alter_column("resubmission_attempt", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("resubmission_attempt")

    # ### end Alembic commands ###
