"""Add RunModel.priority

Revision ID: bca2fdf130bf
Revises: 20166748b60c
Create Date: 2025-05-14 15:24:21.269775

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bca2fdf130bf"
down_revision = "20166748b60c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=True))
    batch_op.execute("UPDATE runs SET priority = 0")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.alter_column("priority", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
