"""Add instances.termination_reason_message

Revision ID: 903c91e24634
Revises: 1aa9638ad963
Create Date: 2025-12-22 12:17:58.573457

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "903c91e24634"
down_revision = "1aa9638ad963"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("termination_reason_message", sa.String(length=4000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("termination_reason_message")

    # ### end Alembic commands ###
