name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to complete this bug report. Before submitting a bug, please ensure that there is no existing issue for the one you have encountered and that you have discussed it with the team via [Slack](https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ).
  - type: input
    id: dstack-version
    attributes:
      label: dstack version
      description: Which dstack version are you using?
      placeholder: ex. 0.1.1
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Which Python version are you using?
      placeholder: ex. 3.9.1
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Which operating system and its version are you using?
      placeholder: e.g. Linux, macOS 13.1, Windows 11, etc
    validations:
      required: true
  - type: input
    id: host-arch
    attributes:
      label: Host Arch
      description: Which architecture are you using?
      placeholder: e.g. x86, ARM
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide the context, exact steps to reproduce, and the expected result.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If the run is local, attach the entire contents of `~/.dstack/tmp/runner/configs/<runner-id>/logs/<runner-id>`.
        
        If the run is remote, attach the logs from the corresponding cloud.
        If it's AWS, the logs can be found in the `/dstack/runners/<bucket>` CloudWatch group in the `<runner-id>` CloudWatch stream (within the configured AWS region).
        If it's GCP, the logs can be found under the `projects/dstack/logs/dstack-runners-<bucket>-<runner-id>` log name.
        To filter out the logs of a particular GCP run, type `dstack-runners <run-name>` into the Logs Explorer search field.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Any links, references or screenshots to have more context about the issue.

        Tip: Attach a minimal sample project to reproduce the issue or provide further log files by clicking into this area to focus it and then dragging files in.