name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to complete this bug report. Before submitting a bug, please ensure that there is no existing issue for the one you have encountered and that you have discussed it with the team via [Discord](https://discord.gg/u8SmfwPpMd).
  - type: input
    id: dstack-version
    attributes:
      label: dstack version
      description: Which dstack version are you using?
      placeholder: ex. 0.1.1
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Which Python version are you using?
      placeholder: ex. 3.9.1
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Which operating system and its version are you using?
      placeholder: e.g. Linux, macOS 13.1, Windows 11, etc
    validations:
      required: true
  - type: input
    id: host-arch
    attributes:
      label: Host Arch
      description: Which architecture are you using?
      placeholder: e.g. x86, ARM
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide the context, the exact steps to reproduce the issue, and the expected behaviour.
    validations:
      required: true
  - type: textarea
    id: cli-logs
    attributes:
      label: CLI logs
      description: |
        Paste the output of `dstack run`. Try setting `DSTACK_CLI_LOG_LEVEL=debug` to get detailed logs.
      render: shell
  - type: textarea
    id: server-logs
    attributes:
      label: Server logs
      description: |
        Paste the output of `dstack server`. Pass `--log-level=debug` to get debug logs.
      render: shell
  - type: textarea
    id: runner-logs
    attributes:
      label: Runner logs
      description: |
        Paste the output of `dstack logs --diagnose <run_name>`.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Any links, references or screenshots to have more context about the issue.

        Tip: Provide further log files by clicking into this area and then dragging the files in.