"""Add run list index

Revision ID: 4ae1a5b0e7f1
Revises: 0e33559e16ed
Create Date: 2024-03-18 12:16:27.991524

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ae1a5b0e7f1"
down_revision = "0e33559e16ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_submitted_at_id", [sa.text("submitted_at DESC"), "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_submitted_at_id")

    # ### end Alembic commands ###
