type: dev-environment
# The name is optional, if not specified, generated randomly
name: llama31-vscode-tgi

# The official TGI Docker image
image: ghcr.io/huggingface/text-generation-inference:latest

# Required environment variables
env:
  - HF_TOKEN
ide: vscode

# Use either spot or on-demand instances
spot_policy: auto
# Uncomment to ensure it doesn't create a new fleet
# creation_policy: reuse

resources:
  # Required resources
  gpu: 24GB
