"""empty message

Revision ID: 3e4c7fa3680b
Revises: 32e5940896ad
Create Date: 2023-08-29 16:17:50.017685

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e4c7fa3680b"
down_revision = "32e5940896ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("run_name", sa.String(length=50), nullable=True),
        sa.Column("project_name", sa.String(length=50), nullable=False),
        sa.Column("job_data", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
            name=op.f("fk_jobs_project_name_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_run_name"), ["run_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_run_name"))

    op.drop_table("jobs")
    # ### end Alembic commands ###
