"""Add default gateway

Revision ID: 842d9dab4d43
Revises: 32e5940896ad
Create Date: 2023-08-23 19:23:00.960188

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "842d9dab4d43"
down_revision = "32e5940896ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_gateway", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("default_gateway")

    # ### end Alembic commands ###
