services:
  app:
    image: ghcr.io/huggingface/chat-ui-db:0.9.5
    environment:
      HF_TOKEN: ${HF_TOKEN?}
      MONGODB_URL: mongodb://db:27017
      MODELS: |
        [{
          "name": "${MODEL_ID?}",
          "endpoints": [{"type": "openai", "baseURL": "http://tgi:8000/v1"}]
        }]
    ports:
      - 127.0.0.1:9000:3000
    depends_on:
      - tgi
      - db

  tgi:
    image: ghcr.io/huggingface/text-generation-inference:3.3.4
    volumes:
      - tgi_data:/data
    environment:
      HF_TOKEN: ${HF_TOKEN?}
      MODEL_ID: ${MODEL_ID?}
      PORT: 8000
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db

volumes:
  tgi_data:
  db_data:
