type: task
name: chat-ui-task

privileged: true
image: dstackai/dind
env:
  - MODEL_ID=meta-llama/Llama-3.2-3B-Instruct
  - HF_TOKEN
working_dir: examples/misc/docker-compose
commands:
  - start-dockerd
  - docker compose up
ports:
  - 9000

# Use either spot or on-demand instances
spot_policy: auto

resources:
  # Required resources
  gpu: "nvidia:24GB"

# Uncomment to persist data
#volumes:
#  - name: my-dind-volume
#    path: /var/lib/docker
