type: dev-environment
# The name is optional, if not specified, generated randomly
name: vscode

#python: "3.11"

image: un1def/dstack-base:py3.12-dev-cuda-12.1

ide: vscode

# Use either spot or on-demand instances
#spot_policy: auto

resources:
  cpu: x86:8..32
  gpu: 24GB..:1
