type: dev-environment
# The name is optional, if not specified, generated randomly
name: vscode

python: "3.11"
# Uncomment to use a custom Docker image
#image: dstackai/base:py3.10-0.5-cuda-12.1

ide: vscode

# Use either spot or on-demand instances
spot_policy: auto

# Uncomment to request resources
#resources:
#  gpu: 24GB