type: object
additionalProperties: false
properties:
  image:
    type: string
  commands:
    type: array
    items:
      type: string
  working_dir:
    type: string
  resources:
    type: object
    properties:
      cpu:
        type: integer
      memory:
        type: string
      gpu:
        type: integer
    additionalProperties: false
  artifacts:
    type: array
    items:
      type: string
  ports:
    type: array
    items:
      type: integer
required:
  - image
