type: task
name: nccl-tests

nodes: 2
startup_order: workers-first
stop_criteria: master-done

image: dstackai/base-stgn:0.11-base-efa
env:
  - NCCL_DEBUG=INFO
commands:
  - |
    sleep infinity

resources:
  gpu: nvidia:1..8
  shm_size: 16GB
