type: dev-environment
# The name is optional, if not specified, generated randomly
name: trl-vscode

# If `image` is not specified, dstack uses its default image
python: "3.10"

# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN
  - ACCELERATE_LOG_LEVEL=info
  - WANDB_API_KEY
# Uncomment if you want the environment to be pre-installed
#init:
#  - conda install cuda
#  - pip install flash-attn --no-build-isolation
#  - pip install "transformers>=4.43.2"
#  - pip install bitsandbytes
#  - pip install peft
#  - pip install wandb
#  - git clone https://github.com/huggingface/trl
#  - cd trl
#  - pip install .

ide: vscode

# Use either spot or on-demand instances
spot_policy: auto

resources:
  gpu:
    # 24GB or more vRAM
    memory: 24GB..
    # One or more GPU
    count: 1..