type: service
name: qwen-nim

image: nvcr.io/nim/qwen/qwen-2.5-7b-instruct:latest
env:
  - NGC_API_KEY
  - NIM_MAX_MODEL_LEN=4096
registry_auth:
  username: $oauthtoken
  password: ${{ env.NGC_API_KEY }}
port: 8000
# Register the model
model: qwen/qwen-2.5-7b-instruct

# Uncomment to leverage spot instances
#spot_policy: auto

# Cache downloaded models
volumes:
  - instance_path: /root/.cache/nim
    path: /opt/nim/.cache
    optional: true

resources:
  gpu: 24GB
  # Uncomment if using multiple GPUs
  shm_size: 16GB
