"""empty message

Revision ID: f111b35eca53
Revises: 
Create Date: 2023-04-07 14:18:15.533468

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f111b35eca53"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("backend", sa.String(length=30), nullable=False),
        sa.Column("config", sa.String(length=300), nullable=False),
        sa.Column("auth", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=200), nullable=False),
        sa.Column("global_role", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_name", sa.String(length=50), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("project_role", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["users.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_project",
        sa.Column("users_name", sa.String(length=50), nullable=True),
        sa.Column("project_name", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
        ),
        sa.ForeignKeyConstraint(
            ["users_name"],
            ["users.name"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_project")
    op.drop_table("members")
    op.drop_table("users")
    op.drop_table("projects")
    # ### end Alembic commands ###
