"""More fleet statuses

Revision ID: 053df66af0a5
Revises: 71a34efe11a3
Create Date: 2024-07-16 15:59:53.211166

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "053df66af0a5"
down_revision = "71a34efe11a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=9),
            type_=sa.Enum(
                "SUBMITTED", "ACTIVE", "TERMINATING", "TERMINATED", "FAILED", name="fleetstatus"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "SUBMITTED", "ACTIVE", "TERMINATING", "TERMINATED", "FAILED", name="fleetstatus"
            ),
            type_=sa.VARCHAR(length=9),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
