"""Add UserModel.deleted and original_name

Revision ID: 06e977bc61c7
Revises: 7d1ec2b920ac
Create Date: 2025-11-26 11:43:34.825686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06e977bc61c7"
down_revision = "7d1ec2b920ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(sa.Column("original_name", sa.String(length=50), nullable=True))

    # For postgres, this was moved to a new migration to avoid deadlocks.
    if op.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("projects", schema=None) as batch_op:
            batch_op.add_column(sa.Column("original_name", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("original_name")
        batch_op.drop_column("deleted")

    # For postgres, this was moved to a new migration to avoid deadlocks.
    if op.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("projects", schema=None) as batch_op:
            batch_op.drop_column("original_name")

    # ### end Alembic commands ###
