"""add_volume_last_job_processed_at

Revision ID: 09f10d63c924
Revises: 35e90e1b0d3e
Create Date: 2025-06-24 11:41:39.588797

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "09f10d63c924"
down_revision = "35e90e1b0d3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_job_processed_at",
                dstack._internal.server.models.NaiveDateTime(),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.drop_column("last_job_processed_at")
    # ### end Alembic commands ###
