"""Added email index

Revision ID: 1aa9638ad963
Revises: 22d74df9897e
Create Date: 2025-12-21 22:08:27.331645

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1aa9638ad963"
down_revision = "22d74df9897e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    # ### end Alembic commands ###
