"""Add JobModel.inactivity_secs

Revision ID: 1e76fb0dde87
Revises: 63c3f19cb184
Create Date: 2025-02-11 23:37:58.823710

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e76fb0dde87"
down_revision = "63c3f19cb184"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("inactivity_secs", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("inactivity_secs")

    # ### end Alembic commands ###
