"""Add events and event_targets

Revision ID: 22d74df9897e
Revises: 5fd659afca82
Create Date: 2025-12-04 20:56:08.003504

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "22d74df9897e"
down_revision = "5fd659afca82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("recorded_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column(
            "actor_user_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_events_actor_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_recorded_at"), ["recorded_at"], unique=False)

    op.create_table(
        "event_targets",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("event_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "entity_project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("entity_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_project_id"],
            ["projects.id"],
            name=op.f("fk_event_targets_entity_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_targets_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_targets")),
    )
    with op.batch_alter_table("event_targets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_targets_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_targets_entity_project_id"), ["entity_project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_targets_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_event_targets_event_id"), ["event_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_targets_event_id"))
        batch_op.drop_index(batch_op.f("ix_event_targets_entity_type"))
        batch_op.drop_index(batch_op.f("ix_event_targets_entity_project_id"))
        batch_op.drop_index(batch_op.f("ix_event_targets_entity_id"))

    op.drop_table("event_targets")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_events_actor_user_id"))

    op.drop_table("events")
    # ### end Alembic commands ###
