"""Make blob nullable

Revision ID: 23e01c56279a
Revises: 14f2cb002fc2
Create Date: 2023-11-06 16:13:00.455543

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23e01c56279a"
down_revision = "14f2cb002fc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("codes", schema=None) as batch_op:
        batch_op.alter_column("blob", existing_type=sa.BLOB(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("codes", schema=None) as batch_op:
        batch_op.alter_column("blob", existing_type=sa.BLOB(), nullable=False)

    # ### end Alembic commands ###
