"""Add FleetModel.consolidation_attempt and FleetModel.last_consolidated_at

Revision ID: 2498ab323443
Revises: e2d08cd1b8d9
Create Date: 2025-08-29 16:08:48.686595

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "2498ab323443"
down_revision = "e2d08cd1b8d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("consolidation_attempt", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_consolidated_at",
                dstack._internal.server.models.NaiveDateTime(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fleets", schema=None) as batch_op:
        batch_op.drop_column("last_consolidated_at")
        batch_op.drop_column("consolidation_attempt")

    # ### end Alembic commands ###
