"""empty message

Revision ID: 252d3743b641
Revises: bfba43f6def2
Create Date: 2023-09-25 16:09:57.816586

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "252d3743b641"
down_revision = "bfba43f6def2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codes",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("repo_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("blob_hash", sa.String(length=4000), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_codes_repo_id_repos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_codes")),
        sa.UniqueConstraint("blob_hash", name=op.f("uq_codes_blob_hash")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("codes")
    # ### end Alembic commands ###
