"""Remove InstanceModel.retry_policy

Revision ID: 29826f417010
Revises: dfffd6a1165c
Create Date: 2024-05-29 10:40:37.904752

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29826f417010"
down_revision = "dfffd6a1165c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("retry_policy")
        batch_op.drop_column("retry_policy_duration")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("retry_policy_duration", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("retry_policy", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
