"""Pipelines

Revision ID: 351efa3432d9
Revises: 706e0acc3a7d
Create Date: 2026-02-17 10:45:48.754096

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "351efa3432d9"
down_revision = "706e0acc3a7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("compute_groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lock_expires_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "lock_token", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.add_column(sa.Column("lock_owner", sa.String(length=100), nullable=True))

    with op.batch_alter_table("placement_groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lock_expires_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "lock_token", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.add_column(sa.Column("lock_owner", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placement_groups", schema=None) as batch_op:
        batch_op.drop_column("lock_owner")
        batch_op.drop_column("lock_token")
        batch_op.drop_column("lock_expires_at")

    with op.batch_alter_table("compute_groups", schema=None) as batch_op:
        batch_op.drop_column("lock_owner")
        batch_op.drop_column("lock_token")
        batch_op.drop_column("lock_expires_at")

    # ### end Alembic commands ###
