"""Add SecretModel

Revision ID: 371e7c58b319
Revises: 35e90e1b0d3e
Create Date: 2025-06-26 11:41:11.277657

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "371e7c58b319"
down_revision = "35e90e1b0d3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "project_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column("updated_at", dstack._internal.server.models.NaiveDateTime(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "value", dstack._internal.server.models.EncryptedString(length=2000), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_secrets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secrets")),
    )
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.create_index("ix_project_id_name", ["project_id", "name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.drop_index("ix_project_id_name")

    op.drop_table("secrets")
    # ### end Alembic commands ###
