"""Fix code uq constraint

Revision ID: 3dbdce90d0e0
Revises: 23e01c56279a
Create Date: 2023-11-14 10:41:52.084668

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3dbdce90d0e0"
down_revision = "23e01c56279a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("codes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_codes_blob_hash", type_="unique")
        batch_op.create_unique_constraint("uq_codes_repo_id_blob_hash", ["repo_id", "blob_hash"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("codes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_codes_repo_id_blob_hash", type_="unique")
        batch_op.create_unique_constraint("uq_codes_blob_hash", ["blob_hash"])

    # ### end Alembic commands ###
