"""drop removed flag

Revision ID: 4f1315a385b8
Revises: 769c6e807b7a
Create Date: 2024-02-28 14:41:29.157274

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f1315a385b8"
down_revision = "769c6e807b7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("removed")

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("processing_finished")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("processing_finished", sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("removed", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False)
        )

    # ### end Alembic commands ###
