"""add pools fix optional

Revision ID: 5395b4ae6c3b
Revises: b55bd09bf186
Create Date: 2024-02-08 11:08:31.426042

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5395b4ae6c3b"
down_revision = "b55bd09bf186"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.alter_column(
            "termination_idle_time",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Integer(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.alter_column(
            "termination_idle_time",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=50),
            nullable=True,
        )

    # ### end Alembic commands ###
