"""Add ix_instances_fleet_id

Revision ID: 5fd659afca82
Revises: d4d9dc26cf58
Create Date: 2025-12-04 20:52:07.015334

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5fd659afca82"
down_revision = "d4d9dc26cf58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instances_fleet_id"), ["fleet_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instances_fleet_id"))

    # ### end Alembic commands ###
