"""Add user emails

Revision ID: 686fb8341ea5
Revises: 3dbdce90d0e0
Create Date: 2023-11-14 16:09:06.039682

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "686fb8341ea5"
down_revision = "3dbdce90d0e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
