"""Add InstanceModel.num

Revision ID: 71a34efe11a3
Revises: 5d7c412fa5dd
Create Date: 2024-07-16 10:44:45.329862

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71a34efe11a3"
down_revision = "5d7c412fa5dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instance_num", sa.Integer(), nullable=True))

    batch_op.execute("UPDATE instances SET instance_num = 0")

    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.alter_column("instance_num", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("instance_num")

    # ### end Alembic commands ###
