"""Add volumes_attachments_table

Revision ID: 721dce879243
Revises: 56f99dc69a42
Create Date: 2024-06-20 14:14:16.323002

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "721dce879243"
down_revision = "56f99dc69a42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volumes_attachments",
        sa.Column("volume_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column(
            "instace_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instace_id"],
            ["instances.id"],
            name=op.f("fk_volumes_attachments_instace_id_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"], ["volumes.id"], name=op.f("fk_volumes_attachments_volume_id_volumes")
        ),
        sa.PrimaryKeyConstraint("volume_id", "instace_id", name=op.f("pk_volumes_attachments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("volumes_attachments")
    # ### end Alembic commands ###
