"""add termination_reason

Revision ID: 769c6e807b7a
Revises: e2dbe6d714b3
Create Date: 2024-02-26 16:30:23.906285

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "769c6e807b7a"
down_revision = "e2dbe6d714b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column("error_code", new_column_name="termination_reason")

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "termination_reason",
                sa.Enum(
                    "JOB_FAILED",
                    "RETRY_LIMIT_EXCEEDED",
                    "STOPPED_BY_USER",
                    "ABORTED_BY_USER",
                    name="runterminationreason",
                ),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                "PENDING",
                "SUBMITTED",
                "STARTING",
                "RUNNING",
                "TERMINATING",
                "TERMINATED",
                "FAILED",
                "DONE",
                name="runstatus",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING",
                "SUBMITTED",
                "STARTING",
                "RUNNING",
                "TERMINATING",
                "TERMINATED",
                "FAILED",
                "DONE",
                name="runstatus",
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=False,
        )
        batch_op.drop_column("termination_reason")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column("termination_reason", new_column_name="error_code")

    # ### end Alembic commands ###
