"""Add InstanceModel.shared_info

Revision ID: 7aab9b6c347a
Revises: 1338b788b612
Create Date: 2025-01-21 13:26:13.602438

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7aab9b6c347a"
down_revision = "1338b788b612"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shared_info", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("shared_info")

    # ### end Alembic commands ###
