"""Add service_spec

Revision ID: 7e65d013399b
Revises: 4f1315a385b8
Create Date: 2024-02-29 17:04:09.701615

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e65d013399b"
down_revision = "4f1315a385b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("service_spec", sa.String(length=4000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("service_spec")

    # ### end Alembic commands ###
