"""Add VolumeModel.volume_attachment_data

Revision ID: 83b058412e71
Revises: 721dce879243
Create Date: 2024-06-24 14:20:17.214961

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83b058412e71"
down_revision = "721dce879243"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("volume_attachment_data", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.drop_column("volume_attachment_data")

    # ### end Alembic commands ###
