"""Add UserModel.deleted

Revision ID: 965760bacf93
Revises: 7d1ec2b920ac
Create Date: 2025-11-25 15:17:05.513712

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "965760bacf93"
down_revision = "7d1ec2b920ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("deleted")

    # ### end Alembic commands ###
