"""instance.termination_reason_message

Revision ID: a16a05249504
Revises: 2498ab323443
Create Date: 2025-10-13 15:29:56.691164

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a16a05249504"
down_revision = "2498ab323443"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("termination_reason_message", sa.String(length=4000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("termination_reason_message")

    # ### end Alembic commands ###
