"""Add JobModel.waiting_master_job

Revision ID: a5bc4573781e
Revises: 2498ab323443
Create Date: 2025-10-14 09:53:02.067538

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5bc4573781e"
down_revision = "2498ab323443"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("waiting_master_job", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("waiting_master_job")

    # ### end Alembic commands ###
