"""Add instances.termination_reason_message

Revision ID: c3de3e67c693
Revises: 22d74df9897e
Create Date: 2025-12-18 20:41:20.376056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3de3e67c693"
down_revision = "22d74df9897e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("termination_reason_message", sa.String(length=4000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instances", schema=None) as batch_op:
        batch_op.drop_column("termination_reason_message")

    # ### end Alembic commands ###
