"""Add UserModel.original_name and ProjectModel.original_name

Revision ID: cc3912316bfd
Revises: 965760bacf93
Create Date: 2025-11-26 11:04:18.383458

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc3912316bfd"
down_revision = "965760bacf93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_name", sa.String(length=50), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_name", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("original_name")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("original_name")

    # ### end Alembic commands ###
