"""Add ix_jobs_run_id

Revision ID: d4d9dc26cf58
Revises: 006512f572b4
Create Date: 2025-12-04 20:48:10.543248

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4d9dc26cf58"
down_revision = "006512f572b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_run_id"))

    # ### end Alembic commands ###
