"""replicas and runs processing

Revision ID: e2dbe6d714b3
Revises: 1a48dfe44a40
Create Date: 2024-02-22 17:13:27.768424

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2dbe6d714b3"
down_revision = "1a48dfe44a40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("replica_num", sa.Integer(), nullable=True))
    batch_op.execute("UPDATE jobs SET replica_num = 0")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column("replica_num", nullable=False)

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_processed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("processing_finished", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "gateway_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_runs_gateway_id_gateways"),
            "gateways",
            ["gateway_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.execute(
        "UPDATE runs SET " "  last_processed_at = submitted_at, " "  processing_finished = 0"
    )
    op.execute(
        "UPDATE runs SET "
        "  processing_finished = 1, "
        "  status = 'TERMINATED' "
        "WHERE id NOT IN ( "
        "  SELECT run_id FROM jobs "
        "  WHERE removed = 0"
        ")"
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.alter_column("last_processed_at", nullable=False)
        batch_op.alter_column("processing_finished", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_runs_gateway_id_gateways"), type_="foreignkey")
        batch_op.drop_column("gateway_id")
        batch_op.drop_column("processing_finished")
        batch_op.drop_column("last_processed_at")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("replica_num")

    # ### end Alembic commands ###
