"""Added fail reason for InstanceModel

Revision ID: ea4cd670dba5
Revises: 29c08c6a8cb3
Create Date: 2024-02-16 18:10:38.805380

"""


# revision identifiers, used by Alembic.
revision = "ea4cd670dba5"
down_revision = "29c08c6a8cb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
