"""Add MemberModel.member_num

Revision ID: ea60480f82bb
Revises: d6b11105f659
Create Date: 2024-08-21 14:20:34.605661

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea60480f82bb"
down_revision = "d6b11105f659"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("member_num", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_column("member_num")

    # ### end Alembic commands ###
