"""Add RunModel.next_triggered_at

Revision ID: ec02a26a256c
Revises: d5863798bf41
Create Date: 2025-07-17 15:47:00.443217

"""

import sqlalchemy as sa
from alembic import op

import dstack._internal.server.models

# revision identifiers, used by Alembic.
revision = "ec02a26a256c"
down_revision = "d5863798bf41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "next_triggered_at", dstack._internal.server.models.NaiveDateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("next_triggered_at")

    # ### end Alembic commands ###
