"""Add JobMetricsPoint

Revision ID: f3048949b671
Revises: a7b46c073fa1
Create Date: 2024-10-11 10:43:35.767284

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3048949b671"
down_revision = "a7b46c073fa1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_metrics_point",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("job_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("timestamp_micro", sa.BigInteger(), nullable=False),
        sa.Column("cpu_usage_micro", sa.BigInteger(), nullable=False),
        sa.Column("memory_usage_bytes", sa.BigInteger(), nullable=False),
        sa.Column("memory_working_set_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_metrics_point_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_metrics_point")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_metrics_point")
    # ### end Alembic commands ###
