"""user.ssh_key

Revision ID: ff1d94f65b08
Revises: 2498ab323443
Create Date: 2025-10-09 20:31:31.166786

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff1d94f65b08"
down_revision = "2498ab323443"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ssh_private_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ssh_public_key", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("ssh_public_key")
        batch_op.drop_column("ssh_private_key")

    # ### end Alembic commands ###
