type: object
additionalProperties: false
properties:
  image:
    type: string
  before_run:
    type: array
    items:
      type: string
  commands:
    type: array
    items:
      type: string
  environment:
    type: object
    additionalProperties: true
  working_dir:
    type: string
  resources:
    type: object
    properties:
      cpu:
        type: integer
      memory:
        type: string
      gpu:
        oneOf:
          - type: integer
          - type: object
            additionalProperties: false
            properties:
              count:
                type: integer
              name:
                type: string
              memory:
                type: string
      shm_size:
        type: string
      interruptible:
        type: boolean
    additionalProperties: false
  artifacts:
    type: array
    items:
      type: string
  ports:
    type: integer
required:
  - image