type: task

python: "3.11"

env:
  - HF_TOKEN
  - HF_HUB_ENABLE_HF_TRANSFER=1

files:
  - requirements.txt
  - train.py

commands:
  - pip install -r requirements.txt
  - tensorboard --logdir results/runs &
  - python train.py --merge_and_push ${{ run.args }}
ports:
  - 6006

resources:
  gpu: 16GB..24GB
